def application(environ, start_response):
    status = '200 OK'
    response_header = [('Content-type', 'text/html')]
    start_response(status, response_header)

    html = ''
    html += ' <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional// \n'
    html += '          EN" "http://www.w3.org/TR/xhtml/DTD/xhtml-transitional.dtd"> \n '
    html += '<html lang="en" dir="ltr"> \n '
    html += '<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> \n'
    html += '<meta name="keywords" content="login, corendon, captiveportal, flight" /> \n '
    html += '<meta name="description" content="login to gain access to the internet" /> \n '
    html += '<meta name="copyright" content="All rights reserved Corendon" /> \n '
    html += '<meta name="publisher" content="InterDefense" /> \n '
    html += '<meta name="author" content="InterDefense" /> \n '
    html += '<!-- Bootstrap framework has been used --> \n '

    html += '<head> \n'
    html += '<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> \n'
    html += '<link rel="shorcut-icon" href="../html/image/icon/favicon.ico"> \n'
    html += '<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate"> \n '
    html += '<meta http-equiv="Pragma" content="no-cache"> \n'
    html += '<meta http-equiv="Expires" content="0"> \n '
    html += '<meta charset="utf-8"> \n'
    html += '<meta name="viewport" content="width=device-width, initial-scale=1.0"> \n'
    html += '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> \n'
    html += '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script> \n'
    html += '<script src="../html/js/bootstrap.min.js"></script> \n'
    html += '<script src="../html/script/slide.js" type="text/javascript"></script> \n'
    html += '<link rel="stylesheet" href="../html/css/bootstrap.css" type="text/css"> \n'
    html += '<link rel="shortcut icon" href="../html/images/splash.jpg" type="image/x-icon"> \n'
    html += '<link rel="stylesheet" type="text/css" href="../html/style.css"> \n'

    html += '<title>$gatewayname Captive Portal.</title> \n'

    html += '<!-- \n'
    html += 'Content: \n'
    html +=        'Nodogsplash (NDS), by default, serves this splash page (splash.html) \n'
    html +=        'when a client device Captive Portal Detection (CPD) process \n'
    html +=        'attempts to send a port 80 request to the Internet. \n'
    html +=        'You may either embed css in this file or use a separate .css file \n'
    html +=        'in the same directory as this file, as demonstrated here. \n'
    html +=        'It should be noted when designing a custom splash page \n'
    html +=        'that for security reasons many CPD implementations: \n'
    html +=                'Immediately close the browser when the client has authenticated. \n'
    html +=                'Prohibit the use of href links. \n'
    html +=                'Prohibit downloading of external files \n'
    html +=                        '(including .css and .js). \n'
    html +=                'Prohibit the execution of javascript. \n'
    html += 'Authentication: \n'
    html +=        'A client is authenticated on submitting an HTTP form, method=get, \n'
    html +=        'passing $authaction, $tok and $redir. \n'
    html +=        'It is also possible to authenticate using an href link to \n'
    html +=        '$authtarget but be aware that many device Captive Portal Detection \n'
    html +=        'processes prohibit href links, so this method may not work with \n'
    html +=        'all client devices. \n'
    html += 'Available variables: \n'
    html +=        'error_msg: $error_msg \n'
    html +=        'gatewayname: $gatewayname \n'
    html +=        'tok: $tok \n'
    html +=        'redir: $redir \n'
    html +=        'authaction: $authaction \n'
    html +=        'denyaction: $denyaction \n'
    html +=        'authtarget: $authtarget \n'
    html +=        'clientip: $clientip \n'
    html +=        'clientmac: $clientmac \n'
    html +=        'clientupload: $clientupload \n'
    html +=        'clientdownload: $clientdownload \n'
    html +=        'gatewaymac: $gatewaymac \n'
    html +=        'nclients: $nclients \n'
    html +=        'maxclients: $maxclients \n'
    html +=        'uptime: $uptime \n'
    html += 'Additional Variables that can be passed back via the HTTP get, \n'
    html += 'or appended to the query string of the authtarget link: \n'
    html +=        'username \n'
    html +=        'password \n'
    html += '--> \n'

    html += '</head> \n'
    html +=  '<body> \n'
    html +=  '<!-- box containing captive portal --> \n'

    html +=  '<div class="container"> \n'
    html +=    '<img style="margin-top:1em; " src="../html/image/Logo_Coredon.png" width="100%"> \n'
    html +=    '<h1>Captive portal</h1> \n'
    html +=    '<h6>Login to gain access to internet</h6> \n'
    html +=    '<!-- Login Form --> \n'
    html +=    '<form method="get" action="$authaction"> \n'
    html +=      '<div class="form-group"> \n'
    html +=        '<label for="name"><b>Name:<b></label> \n'
    html +=        '<input type="name" class="form-control" id="inputName" placeholder="Name on ticket" required> \n'
    html += '<h6>Login to gain access to internet</h6>\n'

    html += '<div class="form-group">\n'
    html += '<label for="ticketNumber"><b>Ticket Number:<b></label>\n'
    html += '<input type="text" class="form-control" id="ticketNumber" aria-describedby="ticketHelp" placeholder="Enter ticket number" required>\n'
    html += '<small id="ticketHelp" class="form-text text-muted">Well never share your info with someone else </small> \n'
    html += '</div>\n'

    html += '<div class="form-group form-check">\n'
    html += '<input type="checkbox" class="form-check-input" id="exampleCheck1">\n'
    html += '<label class="form-check-label" for="exampleCheck1"><small>I accept the terms and service</small></label>\n'
    html += '</div>\n'

    html += '<input type="hidden" name="tok" value="$tok">\n'
    html += '<input type="hidden" name="redir" value="$redir">\n'
    html += '<input style="margin-bottom: 1em;" type="submit"  value="Continue" class="btn btn-primary">\n'
    html += '</form>\n'
    html += '</div>\n'

    html += '<!-- Button to Open the Modal -->\n'
    html += '<button type="button" class="modalbtn btnhelp" data-toggle="modal" data-target="#myModal">\n'
    html += '? \n'
    html += '</button>\n'
    html += '<!-- The Modal -->\n'
    html += '<div class="modal" id="myModal">\n'
    html += '<div class="modal-dialog">\n'
    html += '<div class="modal-content">\n'
    html += '<!-- Modal Header -->\n'
    html += '<div class="modal-header">\n'
    html += '<h4 class="modal-title">Help</h4>\n'
    html += '<button type="button" class="close" data-dismiss="modal">&times;</button>\n'
    html += '</div>\n'

    html += '<!-- Modal body -->\n'
    html += '<div class="modal-body">\n'
    html += '<h5><b>Why can \'t I access internet? </b></h5> \n'
    html += '<h5><b>Where can I find my ticketnumber?</b></h5>\n'
    html += '<h5><b>....</b></h5>\n'
    html += '<h5><b>....</b></h5>\n'
    html += '</div>\n'

    html += '<!-- Modal footer -->\n'
    html += '<div class="modal-footer">\n'
    html += '<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>\n'
    html += '</div>\n'
    html += '</div>\n'
    html += '</div>\n'
    html += '</div>\n'
    html += '</body>\n'
    html += '</html>\n'

    return [bytes(html, 'utf-8')]

if __name__ == '__main__':
     page = application({}, print)
     print(page[0].decode())
